name: Segedi
favicon: null
layout_spectrum: 0.13453443511389196
typography_spectrum: 0.2562906614039093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#44413d'
    - '#dddce6'
    - '#b5aebb'
    - '#bb795d'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
